name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Only run in tags

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Poetry
      uses: abatilo/actions-poetry@v3.0.0

    - name: Install dependencies
      run: poetry install --no-interaction --no-root

    - name: Build project with Poetry and Pyinstaller
      run: make build

    - name: Create Release and Upload Assets
      uses: softprops/action-gh-release@v2.0.8
      with:
        files: |
          dist/swing_tool-*.whl
          dist/swing_tool-*.tar.gz
          dist/swing_cli-*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
